### ISSUE TITLE
Deployment error

### ISSUE THREAD

**Issue by michaelmior** [dell-oss/doradus-openshift-quickstart#1]
I get the error below when trying to deploy.

```
Disclaimer: This is an experimental cartridge that provides a way to try unsupported languages, frameworks, and middleware on OpenShift.
The initial build for the application failed: Shell command '/sbin/runuser -s /bin/sh 55e22d920c1e66aab8000018 -c "exec /usr/bin/runcon 'unconfined_u:system_r:openshift_t:s0:c3,c499' /bin/sh -c \"gear postreceive --init >> /tmp/initial-build.log 2>&1\""' returned an error. rc=255

.Last 10 kB of build output:
onOptions.ServerEncryptionOptions.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/class-use/CFMetaData.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/class-use/EncryptionOptions.ServerEncryptionOptions.InternodeEncryption.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/class-use/TriggerDefinition.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/class-use/DatabaseDescriptor.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/class-use/KSMetaData.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/class-use/Config.DiskFailurePolicy.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/class-use/EncryptionOptions.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/class-use/ColumnDefinition.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/class-use/ColumnDefinition.Type.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/class-use/Schema.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/class-use/CFMetaData.SpeculativeRetry.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/class-use/RequestSchedulerOptions.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/class-use/EncryptionOptions.ClientEncryptionOptions.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/class-use/CFMetaData.Caching.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/Config.InternodeCompression.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/Config.DiskAccessMode.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/ConfigurationLoader.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/ReadRepairDecision.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/Config.RequestSchedulerId.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/YamlConfigurationLoader.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/Config.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/Config.CommitFailurePolicy.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/EncryptionOptions.ServerEncryptionOptions.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/CFMetaData.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/EncryptionOptions.ServerEncryptionOptions.InternodeEncryption.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/TriggerDefinition.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/DatabaseDescriptor.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/package-use.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/KSMetaData.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/Config.DiskFailurePolicy.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/EncryptionOptions.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/ColumnDefinition.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/package-summary.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/package-frame.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/ColumnDefinition.Type.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/Schema.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/CFMetaData.SpeculativeRetry.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/RequestSchedulerOptions.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/EncryptionOptions.ClientEncryptionOptions.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/package-tree.html
dsc-cassandra-2.0.9/javadoc/org/apache/cassandra/config/CFMetaData.Caching.html
dsc-cassandra-2.0.9/javadoc/help-doc.html
dsc-cassandra-2.0.9/javadoc/package-list
dsc-cassandra-2.0.9/javadoc/overview-summary.html
dsc-cassandra-2.0.9/javadoc/deprecated-list.html
dsc-cassandra-2.0.9/javadoc/allclasses-frame.html
dsc-cassandra-2.0.9/javadoc/serialized-form.html
dsc-cassandra-2.0.9/javadoc/stylesheet.css
dsc-cassandra-2.0.9/javadoc/allclasses-noframe.html
dsc-cassandra-2.0.9/javadoc/resources/
dsc-cassandra-2.0.9/javadoc/resources/titlebar.gif
dsc-cassandra-2.0.9/javadoc/resources/titlebar_end.gif
dsc-cassandra-2.0.9/javadoc/resources/background.gif
dsc-cassandra-2.0.9/javadoc/resources/tab.gif
dsc-cassandra-2.0.9/pylib/
dsc-cassandra-2.0.9/pylib/cqlshlib/
dsc-cassandra-2.0.9/pylib/cqlshlib/cqlhandling.py
dsc-cassandra-2.0.9/pylib/cqlshlib/tracing.py
dsc-cassandra-2.0.9/pylib/cqlshlib/saferscanner.py
dsc-cassandra-2.0.9/pylib/cqlshlib/__init__.py
dsc-cassandra-2.0.9/pylib/cqlshlib/pylexotron.py
dsc-cassandra-2.0.9/pylib/cqlshlib/formatting.py
dsc-cassandra-2.0.9/pylib/cqlshlib/displaying.py
dsc-cassandra-2.0.9/pylib/cqlshlib/wcwidth.py
dsc-cassandra-2.0.9/pylib/cqlshlib/tfactory.py
dsc-cassandra-2.0.9/pylib/cqlshlib/helptopics.py
dsc-cassandra-2.0.9/pylib/cqlshlib/util.py
dsc-cassandra-2.0.9/pylib/cqlshlib/cql3handling.py
dsc-cassandra-2.0.9/pylib/cqlshlib/test/
dsc-cassandra-2.0.9/pylib/cqlshlib/test/test_cqlsh_invocation.py
dsc-cassandra-2.0.9/pylib/cqlshlib/test/test_cqlsh_commands.py
dsc-cassandra-2.0.9/pylib/cqlshlib/test/test_cql_parsing.py
dsc-cassandra-2.0.9/pylib/cqlshlib/test/__init__.py
dsc-cassandra-2.0.9/pylib/cqlshlib/test/test_cqlsh_completion.py
dsc-cassandra-2.0.9/pylib/cqlshlib/test/run_cqlsh.py
dsc-cassandra-2.0.9/pylib/cqlshlib/test/cassconnect.py
dsc-cassandra-2.0.9/pylib/cqlshlib/test/test_keyspace_init.cql
dsc-cassandra-2.0.9/pylib/cqlshlib/test/basecase.py
dsc-cassandra-2.0.9/pylib/cqlshlib/test/test_cqlsh_output.py
dsc-cassandra-2.0.9/pylib/cqlshlib/test/ansi_colors.py
dsc-cassandra-2.0.9/pylib/cqlshlib/ssl.py
dsc-cassandra-2.0.9/pylib/setup.py
dsc-cassandra-2.0.9/bin/
dsc-cassandra-2.0.9/bin/sstable2json.bat
dsc-cassandra-2.0.9/bin/sstableupgrade.bat
dsc-cassandra-2.0.9/bin/cqlsh.bat
dsc-cassandra-2.0.9/bin/cassandra.bat
dsc-cassandra-2.0.9/bin/debug-cql
dsc-cassandra-2.0.9/bin/json2sstable.bat
dsc-cassandra-2.0.9/bin/sstableloader.bat
dsc-cassandra-2.0.9/bin/sstableupgrade
dsc-cassandra-2.0.9/bin/sstablekeys.bat
dsc-cassandra-2.0.9/bin/nodetool
dsc-cassandra-2.0.9/bin/sstablescrub.bat
dsc-cassandra-2.0.9/bin/cassandra
dsc-cassandra-2.0.9/bin/stop-server
dsc-cassandra-2.0.9/bin/debug-cql.bat
dsc-cassandra-2.0.9/bin/json2sstable
dsc-cassandra-2.0.9/bin/cassandra-cli
dsc-cassandra-2.0.9/bin/cassandra-shuffle
dsc-cassandra-2.0.9/bin/cassandra-cli.bat
dsc-cassandra-2.0.9/bin/cassandra-shuffle.bat
dsc-cassandra-2.0.9/bin/sstablescrub
dsc-cassandra-2.0.9/bin/cassandra.in.sh
dsc-cassandra-2.0.9/bin/sstablesplit.bat
dsc-cassandra-2.0.9/bin/sstableloader
dsc-cassandra-2.0.9/bin/sstablesplit
dsc-cassandra-2.0.9/bin/sstablekeys
dsc-cassandra-2.0.9/bin/sstable2json
dsc-cassandra-2.0.9/bin/cqlsh
dsc-cassandra-2.0.9/bin/nodetool.bat
+ rm doradus-server-2.2.tar.gz dsc-cassandra-2.0.9-bin.tar.gz
+ mv dsc-cassandra-2.0.9 cassandra
+ mkdir cassandra-data
+ cd cassandra-data
+ mkdir data
+ mkdir saved_caches
+ mkdir commitlog
+ touch system.log
+ cd ../cassandra/conf/
+ sed -ig 's,/var/lib/cassandra,$HOME/app-root/data/cassandra-data,' cassandra.yaml
+ sed -ig s/127.0.0.1/127.6.245.1/g cassandra.yaml
+ sed -ig s/localhost/127.6.245.1/g cassandra.yaml
+ sed -ig s,7000,17000, cassandra.yaml
+ sed -ig s,7001,17001, cassandra.yaml
+ sed -ig s,9160,19160, cassandra.yaml
+ sed -ig s/localhost/127.6.245.1/g cassandra.yaml
+ sed -ig 's,/var/log/cassandra,$HOME/app-root/data/cassandra-data,' log4j-server.properties
+ sed -ig 's,${max_sensible_yg_in_mb}M,256M,' cassandra-env.sh
+ sed -ig 's,${desired_yg_in_mb}M,256M,' cassandra-env.sh
+ sed -ig '/jmxremote/s/^/#/' cassandra-env.sh
Starting DIY cartridge
+ cd /var/lib/openshift/55e22d920c1e66aab8000018/app-root/data//cassandra
+ bin/cassandra
+ export CQLSH_HOST=127.6.245.1
+ CQLSH_HOST=127.6.245.1
+ export CQLSH_PORT=19160
+ CQLSH_PORT=19160
+ sleep 20
Error occurred during initialization of VM
Could not reserve enough space for object heap
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
+ cd /var/lib/openshift/55e22d920c1e66aab8000018/app-root/data//doradus-server/bin/
+ java -cp '../lib/*:../config/*' com.dell.doradus.core.DoradusServer -dbhost 127.6.245.1 -dbport 19160 -restaddr 127.6.245.1 -restport 8080 -storage_services
18:11:34,022 INFO ServerConfig: Trying to load settings from: file:/var/lib/openshift/55e22d920c1e66aab8000018/app-root/data/doradus-server/config/doradus.yaml
18:11:34,284 INFO ServerConfig: Ok. Configuration loaded.
18:11:34,284 INFO ServerConfig: Parsing the command line arguments...
18:11:34,285 ERROR ServerConfig: Fatal configuration error
com.dell.doradus.common.ConfigurationException: A value is expected after: -storage_services
    at com.dell.doradus.core.ServerConfig.parseCommandLineArgs(ServerConfig.java:347)
    at com.dell.doradus.core.ServerConfig.load(ServerConfig.java:170)
    at com.dell.doradus.core.DoradusServer.initConfig(DoradusServer.java:276)
    at com.dell.doradus.core.DoradusServer.initStandAlone(DoradusServer.java:267)
    at com.dell.doradus.core.DoradusServer.main(DoradusServer.java:121)
A value is expected after: -storage_services
Fatal configuration error. Unable to start server.  See log for stacktrace.
18:11:34,298 ERROR DoradusServer: Abnormal shutdown
java.lang.RuntimeException: Failed to initialize server configuration
    at com.dell.doradus.core.DoradusServer.initConfig(DoradusServer.java:278)
    at com.dell.doradus.core.DoradusServer.initStandAlone(DoradusServer.java:267)
    at com.dell.doradus.core.DoradusServer.main(DoradusServer.java:121)
Caused by: com.dell.doradus.common.ConfigurationException: A value is expected after: -storage_services
    at com.dell.doradus.core.ServerConfig.parseCommandLineArgs(ServerConfig.java:347)
    at com.dell.doradus.core.ServerConfig.load(ServerConfig.java:170)
    at com.dell.doradus.core.DoradusServer.initConfig(DoradusServer.java:276)
    ... 2 more
-------------------------
Git Post-Receive Result: failure
Activation status: failure
Activation failed for the following gears:
55e22d920c1e66aab8000018 (Error activating gear: CLIENT_ERROR: Failed to execute: 'control start' for /var/lib/openshift/55e22d920c1e66aab8000018/diy
#<IO:0x000000016642b0>
#<IO:0x00000001664238>
)
Deployment completed with status: failure
postreceive failed
```

**Comment by TraDuong1** [comment]
Hi Michael,

Thanks for trying this "getting-started" simple  project on Doradus on Openshift.
We fixed the issue by removing the extra param and just tested on Openshift again. It works.
Please try again with the same steps listed on the documentation.

Also Doradus can be run in an OpenShift cartridge where Doradus connects to an external Cassandra.
You can follow the instructions from this project https://github.com/TraDuong1/openshift-origin-cartridge-doradus

Thanks.
--Tra
